server:
  port: 20181
  context-path: /api/accounts
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  jooq:
    sql-dialect: MYSQL
  datasource:
      platform: mysql
      url: jdbc:mysql://broker:3306/uaa?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: fengshuaiju
      initialization-mode: never
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  cloud:
    stream:
      bindings:
        output:
          destination: feng.uaa.notifications
        from-self:
          group: feng.uaa
          destination: feng.uaa.notifications
  output.ansi.enabled: always
  
  rabbitmq:
    host: broker
    port: 5672


eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        key-value: staging

qcloud.sms:
  appId: 1400090446
  appKey: 4e74febbc3af5c8de6f58413a2f6d8fd
  sign: 运抵达

wechat:
  appId: wx1fe3c29affa59694
  appSecret: e6dc7ab176842b4902d9d68adf193d16

---
spring:
  profiles: development

logging:
  level:
    org.springframework.security: DEBUG


---

spring.profiles: staging

logging:
  file: ${user.home}/logs/accounts.log
